const pre = 'hackatown2018/task/';

export default {
  FETCH_TASKS: `${pre}FETCH_TASKS`,
  FETCH_TASKS_SUCCESS: `${pre}FETCH_TASKS_SUCCESS`,
  FETCH_TASKS_FAILURE: `${pre}FETCH_TASKS_FAILURE`,

  CREATE_TASK: `${pre}CREATE_TASK`,
  CREATE_TASK_SUCCESS: `${pre}CREATE_TASK_SUCCESS`,
  CREATE_TASK_FAILURE: `${pre}CREATE_TASK_FAILURE`,

  UPDATE_TASK: `${pre}UPDATE_TASK`,
  UPDATE_TASK_SUCCESS: `${pre}UPDATE_TASK_SUCCESS`,
  UPDATE_TASK_FAILURE: `${pre}UPDATE_TASK_FAILURE`
};
