version: '3'

networks:
  front:
  back:

services:
  frontend:
    build: ./Frontend
    links:
      - backend
    networks:
      - front
    ports:
      - "80:3000"
    restart: always

  backend:
    build: ./Backend
    environment:
      MONGODB_URI: "mongodb://db/hackatown2018"
      SECRET: "hwhk7lumNzVTldE9dNRblx0r1e5YFyjq"
      SEED: "true"
    links:
      - db
    networks:
      - front
      - back
    ports:
      - "8080:8080"
    restart: always

  db:
    image: mongo
    networks:
      - back
    restart: always
    volumes:
      - configdb:/data/configdb
      - db:/data/db

volumes:
  configdb:
  db:
