version: '3'

networks:
  front:
  back:
  web:

services:
  frontend:
    build: ./Frontend
    environment:
      VIRTUAL_HOST: "caremmunity.archsirius.com"
      VIRTUAL_PORT: "3000"
    links:
      - backend
    networks:
      - front
    restart: always

  backend:
    build: ./Backend
    environment:
      MONGODB_URI: "mongodb://db/hackatown2018"
      SECRET: "hwhk7lumNzVTldE9dNRblx0r1e5YFyjq"
      SEED: "false"
      VIRTUAL_HOST: "api.caremmunity.archsirius.com"
      VIRTUAL_PORT: "8080"
    links:
      - db
    networks:
      - front
      - back
    restart: always

  db:
    image: mongo
    networks:
      - back
    restart: always
    volumes:
      - configdb:/data/configdb
      - db:/data/db

  nginx:
    image: nginx
    networks:
      - front
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  nginx-gen:
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    image: jwilder/docker-gen
    networks:
      - front
      - web
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  configdb:
  db:
